name: Android CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/*.apk

  deploy:
    name: Deploy to GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.event_name == 'push'
    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release-apk
        path: ./release-apk

    - name: Create/Update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: CI/CD Release
        name: ${{ github.sha }} - ${{ github.event.head_commit.message }}
        files: ./release-apk/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
